### ISSUE TITLE
Axes rendered incorrectly

### ISSUE THREAD

**Issue by j1234d2003** [fsmMLK/inkscapeMadeEasy#10]
With latest inkscapeMadeEasy, inkscapeCartesianPlotFunction2D and inkscapeCartesianPlotData2D extensions to inkscape 0.91 on Ubuntu 16.04, the text in each label for all axes is vertically flipped.

The same problem happens with your inkscapeExtCartesianPlot extension on same installation of inkscape and inkscapeMadeEasy. Therefore, assuming this is a inkscapeMadeEasy issue, I am reporting it here.

The attached file badCos.png was created using inkscapeCartesianPlotFunction2D using dialog badCosDialog.png. The resulting svg file is also attached as badCos.svg.txt with extension changed to txt instead of svg to allow upload here.

![badCos](https://user-images.githubusercontent.com/2636821/72286045-f61e2e00-3609-11ea-9052-f3b491207c71.png)
![badCosDialog](https://user-images.githubusercontent.com/2636821/72286047-f61e2e00-3609-11ea-95f3-27ffda884c9f.png)
[badCos.svg.txt](https://github.com/fsmMLK/inkscapeMadeEasy/files/4055436/badCos.svg.txt)

**Comment by fsmMLK** [comment]
are you using pstoedit or pdf2svg?

**Comment by fsmMLK** [comment]
I am closing this issue since there is another about the same. Anyway, the most updated version of inkscapeMadeEasy I uploaded today will hopefully solve this issue. However it will take some time for me to update all my plugins.
