### ISSUE TITLE
Mirrored text

### ISSUE THREAD

**Issue by DetroitRC** [fsmMLK/inkscapeMadeEasy#12]
Hi, first of all, i have to say ¡congratulations! it's fantastic what you've been doign with inkscapeMadeEasy.

Now, the problem i encountered is that, when i enable LaTex support, everything looks great with the drawings except for the text labels which appear mirrored. I tested cartesianPlotFunction2D and circuitSymbols, both with the same issue. 

I'm using Inkscape 0.92.5 and the latest versions of your projects. Also, i though it was a problem of TexText, but it seems to be working just fine.

I'm using Inkscape 0.92.5 and the latest versions of your projects. Also, i though it was a problem of TexText, but it seems to be working just fine.

![NoLaTex](https://user-images.githubusercontent.com/70000435/90857117-0e48ef00-e349-11ea-8e57-5fbab6dded34.PNG) ![LaTex](https://user-images.githubusercontent.com/70000435/90857089-fe310f80-e348-11ea-9609-08600c7b0696.PNG)

![prueba](https://user-images.githubusercontent.com/70000435/90857235-4c461300-e349-11ea-8ee3-ef6e53b7d489.PNG)

**Comment by fsmMLK** [comment]
can you send me a svg with the resulting flipped text?

**Comment by DetroitRC** [comment]
[Test.zip](https://github.com/fsmMLK/inkscapeMadeEasy/files/5112667/Test.zip)

**Comment by fsmMLK** [comment]
I am at the moment working on changing all my inkscape plugins to inkscape 1.0. It will now use a much newer version of textext that will (should?) solve this issue you are having.

**Comment by fsmMLK** [comment]
the most updated version of inkscapeMadeEasy I uploaded today will hopefully solve this issue. However it will take some time for me to update all my plugins.
