### ISSUE TITLE
Spostati lungo il sentiero

### ISSUE THREAD

**Issue by Deltaplc** [fsmMLK/inkscapeMadeEasy#16]
Good morning, sorry for my english, I use a translator!
I see you've made quite a few extensions for inkscape. Thanks for all you do!! I wanted to ask if there is an extension to do something like the one you use in this video ( https://youtu.be/9YWeWPmIiNw?t=1102 ) with coreldraw at 18:48 at 18:58.It looks like " move on path" But it's not like that...because it doesn't deform the objects!! It's something similar to the "scatter" extension....Can you help me in any way?

I tried doing a targeted search on the web but unfortunately no one seems to have done anything to solve my problem.
By grouping and then running the "generate from path" >> "move along path" you get a result similar to what I need... but unfortunately there is object distortion!
I attach the screenshots below.

![2](https://user-images.githubusercontent.com/49638681/211288507-0d77caac-9885-43ab-bb51-6ae32d9e3270.png)
![1](https://user-images.githubusercontent.com/49638681/211324227-024ddbd6-def7-4cdc-aea8-1a2f543327a0.png)

I tried to have a look at the .py files related to the extension (in version 0.95 there was one more option) but it seems to use some function that deliberately distorts the objects.....
I think it's not necessary to create a new extension, maybe you can just modify this by adding an option to prevent it from distorting objects.
Unfortunately I'm not able to make these changes... I hope when you have some time you can take a look!!
Thanks again for your availability!
A greeting
David

**Comment by fsmMLK** [comment]
I am not aware of such extension.

It would be possible to write an extension to do that, but it would require time.

**Comment by Deltaplc** [comment]
Thank you so much for your answer!

I changed the second image I had accidentally uploaded 2 of the same!

Maybe if you have some spare time you can write it yourself :)!
Greetings
David

**Comment by Molonky500** [comment]
You have to set the parameters you prefer in the pattern along path tool settings, move around the spacing values and the tangent, also make sure the setting isnt on Repeated Stretched and just the Repeat setting is on, click on pattern is vertical it might also help .

**Comment by Deltaplc** [comment]
HI
Thanks for your help.
The problem is that using the pattern along path extension, the pattern that is placed on the path gets deformed!
If you watch the video, the extension it uses with coreldraw does NOT warp the copied pattern!
Saluti
Davide
