### ISSUE TITLE
Subject: Compatibility with the new version of TexText

### ISSUE THREAD

**Issue by ZiyangYE** [fsmMLK/inkscapeMadeEasy#18]
Currently, Inkscapemadeeasy seems to only support TexText version 1.0, which in turn only supports up to Inkscape version 1.0.x. 
Is there any plan to update the compatibility with new versions of TexText so that the newer versions of Inkscape can be used?

**Comment by fsmMLK** [comment]
I will take a look at this issue ASAP

**Comment by fsmMLK** [comment]
please check the new version.

**Comment by ZiyangYE** [comment]
**I tried the latest version, along with the latest version of logicGates, TexText 1.10.2, and Inkscape 1.4. Unfortunately, I encountered an error. Is this due to inkscapeMadeEasy or logicGates?**


Traceback (most recent call last): File "/home/lakka/.config/inkscape/extensions/textext/base.py", line 569, in tex_to_pdf exec_command([tex_command, self.tmp('tex')] + self.LATEX_OPTIONS) File "/home/lakka/.config/inkscape/extensions/textext/utility.py", line 268, in exec_command raise TexTextCommandFailed(message="Command %s failed (code %d)" % (' '.join(cmd), p.returncode), textext.errors.TexTextCommandFailed: Command /usr/bin/pdflatex tmp.tex -interaction=nonstopmode -halt-on-error failed (code 1)

During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/lakka/.config/inkscape/extensions/logicGates/logicGates.py", line 764, in <module> logic.run() File "/usr/share/inkscape/extensions/inkex/base.py", line 252, in run self.save_raw(self.effect()) File "/home/lakka/.config/inkscape/extensions/logicGates/logicGates.py", line 201, in effect self.drawV(root_layer, position, angleDeg=so.signalRot, nodalVal=text, drawLine=so.signalDrawLine) File "/home/lakka/.config/inkscape/extensions/logicGates/logicGates.py", line 532, in drawV temp = inkDraw.text.latex(self, group, value, pos_text, fontSize=self.fontSize, refPoint=justif, preambleFile=self.preambleFile) File "/home/lakka/.config/inkscape/extensions/inkscapeMadeEasy/inkscapeMadeEasy_Draw.py", line 1408, in latex tex.run([r'--text=' + LatexCommands + LaTeXtext, '--scale-factor=1', '--preamble-file=' + preambleFile, tempFilePath], File "/usr/share/inkscape/extensions/inkex/base.py", line 252, in run self.save_raw(self.effect()) File "/home/lakka/.config/inkscape/extensions/textext/base.py", line 288, in effect self.do_convert(new_text, File "/home/lakka/.config/inkscape/extensions/textext/base.py", line 370, in do_convert converter.tex_to_pdf(tex_executable, text, preamble_file) File "/home/lakka/.config/inkscape/extensions/textext/base.py", line 573, in tex_to_pdf raise TexTextConversionError(parsed_log, error.return_code, error.stdout, error.stderr) textext.errors.TexTextConversionError: ! LaTeX Error: File `siunitx.sty' not found.

**Comment by fsmMLK** [comment]
" File `siunitx.sty' not found."

Verify you installed siunitx latex package.

**Comment by ZiyangYE** [comment]
With texlive-full installed, it works now!

**Comment by fsmMLK** [comment]
usually texlive-science package solves the issue with siunitx.

**Comment by ZiyangYE** [comment]
> usually texlive-science package solves the issue with siunitx.

Well, I installed texlive-science first. But it comes up with new dependencies. So I just installed full...
