### ISSUE TITLE
Error drawing a simple resistor

### ISSUE THREAD

**Issue by darkdragon-001** [fsmMLK/inkscapeMadeEasy#4]
The plugin aborts at [inkscapeMadeEasy_Base.py#L833](https://github.com/fsmMLK/inkscapeMadeEasy/blob/master/inkscapeMadeEasy_Base.py#L833) because the array `listCoords` is empty. This is because `element` is a group and contains only itself.

**Comment by darkdragon-001** [comment]
This problem seemed to go away after adding a preamble .tex file. Anyway, a better error handling with more useful error messages would be nice :)

**Comment by darkdragon-001** [comment]
When I return an empty array in that case, the text is far away from the resistor...

**Comment by fsmMLK** [comment]
I am uploading a newer version soon. Please check if you are using pstoedit converter.
