### ISSUE TITLE
update textextlib to 0.11

### ISSUE THREAD

**Issue by GongSiqiu** [fsmMLK/inkscapeMadeEasy#5]
I can't use your plugins that use textext with my inkscape 0.92.4 . It seems that the old version textext is not compatible with it. Could you consider updating the textextlib

Traceback (most recent call last):
  File "cartesianAxes2D.py", line 90, in <module>
    axis.affect()
  File "/usr/local/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "cartesianAxes2D.py", line 85, in effect
    xGrid=so.xGrid, yGrid=so.yGrid, forceTextSize=textSize, forceLineWidth=lineWidthAxis)
  File "/home/g/.config/inkscape/extensions/inkscapeMadeEasy_Plot.py", line 464, in cartesian
    inkDraw.text.latex(ExtensionBaseObj, groupTicks, xText, [posX + offsetX, axisOrigin[1] + offsetY], textSizeSmall, refPoint=justif)
  File "/home/g/.config/inkscape/extensions/inkscapeMadeEasy_Draw.py", line 1232, in latex
    tex.affect([r'--text=' + LatexCommands + LaTeXtext, '--scale-factor=1', '--preamble-file=' + ExtensionBaseObj.getBasicLatexPackagesFile(), tempFilePath], output=False)
  File "/usr/local/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "/home/g/.config/inkscape/extensions/textextLib/textext.py", line 151, in effect
    self.options.scale_factor, converter_cls, old_node)
  File "/home/g/.config/inkscape/extensions/textextLib/textext.py", line 165, in do_convert
    new_node = converter.convert(text, preamble_file, scale_factor)
  File "/home/g/.config/inkscape/extensions/textextLib/textext.py", line 533, in convert
    self.pdf_to_svg()
  File "/home/g/.config/inkscape/extensions/textextLib/textext.py", line 631, in pdf_to_svg
    + pstoeditOpts)
  File "/home/g/.config/inkscape/extensions/textextLib/textext.py", line 374, in exec_command
    % (' '.join(cmd), p.returncode, out + err))
RuntimeError: Command pstoedit -f plot-svg /tmp/tmpj1pard/tmp.pdf /tmp/tmpj1pard/tmp.svg -dt -ssp -psarg -r9600x9600 failed (code 1): pstoedit: version 3.73 / DLL interface 108 (built: Jul 11 2018 - release build - g++ 7.3.0 - 64-bit) : Copyright (C) 1993 - 2018 Wolfgang Glunz
Error: /undefined in .makeoperator
Operand stack:
   false   rectfill   rectfill   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1991   1   3   %oparray_pop   1990   1   3   %oparray_pop   1978   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1035/1123(G)--   --dict:0/20(G)--   --dict:216/300(L)--   --dict:1035/1123(G)--
Current allocation mode is global
Current file position is 14845
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
PostScript/PDF Interpreter finished. Return status 256 executed command : gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS -r9600x9600 "/tmp/psinApIwgE"
The interpreter seems to have failed, cannot proceed !

**Comment by fsmMLK** [comment]
It seems to be a pstoedit vs. ghostscript compatibility issue. (https://sourceforge.net/p/pstoedit/bugs/25/?limit=25)
I have seen these problems in the past. From the link above, you can try to revert GS to 9.26

I am not sure if it helps you, I am currently using:

-pstoedit: version 3.70 / DLL interface 108 (built: Aug 29 2017 - release build - g++ 7.2.0 - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz

-ghostscript: GPL Ghostscript 9.26 (2018-11-20)

**Comment by GongSiqiu** [comment]
Thanks for your reply. I have downgraded pstoedit to 3.70-3+b2 and ghostscript to 9.26a~dfsg-0+deb9u4. But this problem still appears.

**Comment by fsmMLK** [comment]
Are you sure inkscape is now using the downgraded versions?

**Comment by GongSiqiu** [comment]
This issue has been fixed  [here](https://sourceforge.net/p/pstoedit/bugs/25/?limit=25)
I upgraded pstoedit to 3.75 and solved this problem.
Thank you!
