### ISSUE TITLE
Inkscape 1.0 API changes

### ISSUE THREAD

**Issue by doctormo** [fsmMLK/inkscapeMadeEasy#9]
Hi there,

This is your friendly upstream developer letting you know that the Inkscape API for inkex has changed (significantly) for the 1.0 release. A lot of code will still work (if it works with python3) with the deprecated shim code, but this will produce warnings for your users.

i am available to any extension author who wants to know more about the API on rocket chat over at chat.inkscape.org (the extensions channel).

The new code can be found at https://gitlab.com/inkscape/extensions with many examples of uses of the new API as well as code that is mid-way through being upgraded (because there is a LOT of code).

I notice your code here contains a lot of really cool ideas. If you are interested in pushing some of the functionality into the new inkex API, I'd be very grateful to have the functionality increased. The aim to standardise extensions creation (and testing) so we can support extension authors better.

Thanks for your time.

**Comment by fsmMLK** [comment]
inkscapeMadeEasy 1.0 is out! =D

At the moment inkscapeMadeEasy v1.0 is not compatible with all my plugins. I will update them to be compatible ASAP. There is a table in the main page of the repository with the current status of the updates.

ps: I am closing this issue.
